export const ACTION = {
    LOGIN_USER: "LOGIN_USER",
    LOGOUT_USER: "LOGOUT_USER",
    UPDATE_AVATAR: "UPDATE_AVATAR",
    UPDATE_USER_BOOKS: "UPDATE_USER_BOOKS",
    UPDATE_CURRENTLY_SELLING: "UPDATE_CURRENTLY_SELLING"
}