export const ACTION = {
    LOGIN_USER: "LOGIN_USER",
    LOGOUT_USER: "LOGOUT_USER",
    UPDATE_AVATAR: "UPDATE_AVATAR",
    FETCHING_START: "FETCHING_START",
    FETCHING_COMPLETED: "FETCHING_COMPLETED"
}